name: jj

on:
  push:
    branches: [ "main" ]
env:
  SOURCE_FOLDER: src
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  run-selene-linter:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install NPM
        uses: actions/setup-node@v4
      - name: Install jj
        run: npm install -g pretty-mini-json
      - name: Run jj
        run: jj -u < $SOURCE_FOLDER/data/main.json